# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --unshallow
    post_install:
      - python -m pip install -e .

sphinx:
  configuration: doc/src/conf.py

python:
  install:
    - requirements: .rtd-require
