name: Check ReST input files
on:
  push:
    branches:
      - develop
      - master
  pull_request:
jobs:
  doc8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: doc8-check
        uses: deep-entertainment/doc8-action@v4
        with:
          scanPaths: "doc/src"
